apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  volumes:
    - name: "kuard-data"
      hostPath:
        path: "/var/lib/kuard"
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      volumeMounts:
        - mountPath: "/data"
          name: "kuard-data"
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        #every 5 seconds kubernetes calls this endpoint to see if the pod is healthy
        periodSeconds: 4
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        #every 30 seconds kubernetes calls this endpoint to see if the pod is ready
        initialDelaySeconds: 15
        timeoutSeconds: 1
        periodSeconds: 4
        failureThreshold: 3
